project 'IDEA_cocoapods.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IDEA_cocoapods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDEA_cocoapods
pod 'PMSuperButton'
pod 'Alamofire'

end
