project 'IDEA_NetworkHandler.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IDEA_NetworkHandler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IDEA_NetworkHandler
  
  pod 'Alamofire'

end
